[package]
name = "get-signatures-for-address"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
solana-client = "2.1.0"
solana-pubkey = "2.1.0"
solana-sdk = "2.1.0"
tokio = { version = "1.41.0", features = ["full"] }
